  <div class="col-sm-3 col-md-2 sidebar">
    <ul class="nav nav-sidebar">
      	<li <?php if ($this->uri->segment(1, 0) === 'dashboard'): ?>class="active"<?php endif ?>><a href="<?php echo site_url('dashboard/index'); ?>"><span class="fa fa-fw fa-home" aria-hidden="true"></span> Tablero Principal <?php if ($this->uri->segment(1, 0) === 'dashboard'): ?><span class="sr-only">(current)</span><?php endif ?></a></li>
		
		<h3>Centro de Operaciones</h3>
      	<li <?php if ($this->uri->segment(1, 0) === 'estadisticas'): ?>class="active"<?php endif ?>><a target="_get" href="<?php echo site_url('pdf/estadisticas'); ?>"><span class="fa fa-fw fa-file-pdf-o" aria-hidden="true"></span> Estad&iacute;stica <?php if ($this->uri->segment(1, 0) === 'estadisticas'): ?><span class="sr-only">(current)</span><?php endif ?></a></li>
		<li <?php if ($this->uri->segment(1, 0) === 'documentos_1'): ?>class="active"<?php endif ?>><a href="<?php echo site_url('documentos_1/index'); ?>"><span class="fa fa-fw fa-table" aria-hidden="true"></span> Accidentes  de Transitos <?php if ($this->uri->segment(1, 0) === 'documentos_1'): ?><span class="sr-only">(current)</span><?php endif ?></a></li>
		<li <?php if ($this->uri->segment(1, 0) === 'documentos_2'): ?>class="active"<?php endif ?>><a href="<?php echo site_url('documentos_2/index'); ?>"><span class="fa fa-fw fa-table" aria-hidden="true"></span> Servicios de Ambulancias <?php if ($this->uri->segment(1, 0) === 'documentos_2'): ?><span class="sr-only">(current)</span><?php endif ?></a></li>
		<li <?php if ($this->uri->segment(1, 0) === 'documentos_3'): ?>class="active"<?php endif ?>><a href="<?php echo site_url('documentos_3/index'); ?>"><span class="fa fa-fw fa-table" aria-hidden="true"></span> Incendios de Estructuras <?php if ($this->uri->segment(1, 0) === 'documentos_3'): ?><span class="sr-only">(current)</span><?php endif ?></a></li>
		<li <?php if ($this->uri->segment(1, 0) === 'documentos_4'): ?>class="active"<?php endif ?>><a href="<?php echo site_url('documentos_4/index'); ?>"><span class="fa fa-fw fa-table" aria-hidden="true"></span> Incendios Vehiculares <?php if ($this->uri->segment(1, 0) === 'documentos_4'): ?><span class="sr-only">(current)</span><?php endif ?></a></li>
		<li <?php if ($this->uri->segment(1, 0) === 'documentos_5'): ?>class="active"<?php endif ?>><a href="<?php echo site_url('documentos_5/index'); ?>"><span class="fa fa-fw fa-table" aria-hidden="true"></span> Incendios Forestal y Vegetación <?php if ($this->uri->segment(1, 0) === 'documentos_5'): ?><span class="sr-only">(current)</span><?php endif ?></a></li>
		<li <?php if ($this->uri->segment(1, 0) === 'documentos_6'): ?>class="active"<?php endif ?>><a href="<?php echo site_url('documentos_6/index'); ?>"><span class="fa fa-fw fa-table" aria-hidden="true"></span> Servicio Especial <?php if ($this->uri->segment(1, 0) === 'documentos_6'): ?><span class="sr-only">(current)</span><?php endif ?></a></li>
		<li <?php if ($this->uri->segment(1, 0) === 'documentos_7'): ?>class="active"<?php endif ?>><a href="<?php echo site_url('documentos_7/index'); ?>"><span class="fa fa-fw fa-table" aria-hidden="true"></span> Guardia de Seguridad Prevención <?php if ($this->uri->segment(1, 0) === 'documentos_7'): ?><span class="sr-only">(current)</span><?php endif ?></a></li>
		
		<h3>Archivos Vehiculos</h3>
		<li <?php if ($this->uri->segment(1, 0) === 'marcas'): ?>class="active"<?php endif ?>><a href="<?php echo site_url('marcas/index'); ?>"><span class="fa fa-fw fa-folder" aria-hidden="true"></span> Marcas <?php if ($this->uri->segment(1, 0) === 'marcas'): ?><span class="sr-only">(current)</span><?php endif ?></a></li>
		<li <?php if ($this->uri->segment(1, 0) === 'modelos'): ?>class="active"<?php endif ?>><a href="<?php echo site_url('modelos/index'); ?>"><span class="fa fa-fw fa-folder" aria-hidden="true"></span> Modelos <?php if ($this->uri->segment(1, 0) === 'modelos'): ?><span class="sr-only">(current)</span><?php endif ?></a></li>
		<li <?php if ($this->uri->segment(1, 0) === 'tipos'): ?>class="active"<?php endif ?>><a href="<?php echo site_url('tipos/index'); ?>"><span class="fa fa-fw fa-folder" aria-hidden="true"></span> Tipos <?php if ($this->uri->segment(1, 0) === 'tipos'): ?><span class="sr-only">(current)</span><?php endif ?></a></li>
		<li <?php if ($this->uri->segment(1, 0) === 'clases'): ?>class="active"<?php endif ?>><a href="<?php echo site_url('clases/index'); ?>"><span class="fa fa-fw fa-folder" aria-hidden="true"></span> Clases <?php if ($this->uri->segment(1, 0) === 'clases'): ?><span class="sr-only">(current)</span><?php endif ?></a></li>
		<li <?php if ($this->uri->segment(1, 0) === 'colores'): ?>class="active"<?php endif ?>><a href="<?php echo site_url('colores/index'); ?>"><span class="fa fa-fw fa-folder" aria-hidden="true"></span> Colores <?php if ($this->uri->segment(1, 0) === 'colores'): ?><span class="sr-only">(current)</span><?php endif ?></a></li>
		
		<h3>Archivos Geograficos</h3>
		<li <?php if ($this->uri->segment(1, 0) === 'estados'): ?>class="active"<?php endif ?>><a href="<?php echo site_url('estados/index'); ?>"><span class="fa fa-fw fa-folder" aria-hidden="true"></span> Estados <?php if ($this->uri->segment(1, 0) === 'estados'): ?><span class="sr-only">(current)</span><?php endif ?></a></li>
		<li <?php if ($this->uri->segment(1, 0) === 'municipios'): ?>class="active"<?php endif ?>><a href="<?php echo site_url('municipios/index'); ?>"><span class="fa fa-fw fa-folder" aria-hidden="true"></span> Municipios <?php if ($this->uri->segment(1, 0) === 'municipios'): ?><span class="sr-only">(current)</span><?php endif ?></a></li>
		<li <?php if ($this->uri->segment(1, 0) === 'parroquias'): ?>class="active"<?php endif ?>><a href="<?php echo site_url('parroquias/index'); ?>"><span class="fa fa-fw fa-folder" aria-hidden="true"></span> Parroquias <?php if ($this->uri->segment(1, 0) === 'parroquias'): ?><span class="sr-only">(current)</span><?php endif ?></a></li>
		
		<h3>Configuraci&oacute;n</h3>
		<li <?php if ($this->uri->segment(1, 0) === 'administradores'): ?>class="active"<?php endif ?>><a href="<?php echo site_url('administradores/index'); ?>"><span class="fa fa-fw fa-user-plus" aria-hidden="true"></span> Administradores <?php if ($this->uri->segment(1, 0) === 'administradores'): ?><span class="sr-only">(current)</span><?php endif ?></a></li>
		<li <?php if ($this->uri->segment(1, 0) === 'backup'): ?>class="active"<?php endif ?>><a href="<?php echo site_url('dashboard/backup'); ?>"><span class="fa fa-fw fa-gears" aria-hidden="true"></span> Backup DataBase <?php if ($this->uri->segment(1, 0) === 'backup'): ?><span class="sr-only">(current)</span><?php endif ?></a></li>
    </ul>

  </div>